// Generated by Vision Point II DocsBuilder.
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  "sdkSidebar": [
    {
      "type": "autogenerated",
      "dirName": "."
    }
  ]
};

export default sidebars;
